//Product
export const PRODUCT_REQUEST_RESPONSE = 'LIST_REQUEST_RESPONSE';
export const PRODUCT_REQUEST_SUCCESS = 'LIST_REQUEST_SUCCESS';
export const PRODUCT_REQUEST_FAIL = 'LIST_REQUEST_FAIL';

//Product Detaıls
export const PRODUCTDETAİL_REQUEST_RESPONSE = 'PRODUCTDETAİL_REQUEST_RESPONSE';
export const PRODUCTDETAİL_REQUEST_SUCCESS = 'PRODUCTDETAİL_REQUEST_SUCCESS';
export const PRODUCTDETAİL_REQUEST_FAIL = 'PRODUCTDETAİL_REQUEST_FAIL';
//User Login
export const USER_SIGNIN_RESPONSE = 'USER_SIGNIN_RESPONSE';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';
//User Register
export const USER_REGISTER_RESPONSE = 'USER_REGISTER_RESPONSE ';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

//User Register
export const USER_LOGOUT_ITEM = "USER_LOGOUT_ITEM";

//Cart
export const CARD_ITEM_ADD = 'CARD_ITEM_ADD';
export const CARD_ITEM_DELETE = "CARD_ITEM_DELETE";


