export const PRODUCT_REQUEST_RESPONSE = 'LIST_REQUEST_RESPONSE';
export const PRODUCT_REQUEST_SUCCESS = 'LIST_REQUEST_SUCCESS';
export const PRODUCT_REQUEST_FAIL = 'LIST_REQUEST_FAIL';

export const PRODUCTDETAİL_REQUEST_RESPONSE = 'PRODUCTDETAİL_REQUEST_RESPONSE';
export const PRODUCTDETAİL_REQUEST_SUCCESS = 'PRODUCTDETAİL_REQUEST_SUCCESS';
export const PRODUCTDETAİL_REQUEST_FAIL = 'PRODUCTDETAİL_REQUEST_FAIL';